name: Deploy - Production

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@4a03da89e5c43da56e502053be4bbcb293411883
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/Docker/saigyou-ayakash
            git pull
            yarn install
            yarn build
            docker restart web-api
